### ISSUE TITLE
Tycho does not support Embed-Dependency

### ISSUE THREAD

**Issue by kompiro** [sonatype/sonatype-tycho#10]
When I set Embed-Dependency in pom.xml, "An internal error occurred null" is shown in Console View.
Unfortunately, there is no log about the error.
Please check the issue.

**Comment by ifedorenko** [comment]
please use eclipse bugzilla to submit new tycho bugreports (or did you mean m2eclipse-tycho?)

**Comment by kompiro** [comment]
Oh thank you, now I use m2e and Tycho Project Configuration. so I registered the issue on github.Is this case I should use eclipse bugzilla?

**Comment by ifedorenko** [comment]
please report issues with m2e-tycho to https://github.com/sonatype/m2eclipse-tycho project
