### ISSUE TITLE
tycho-demo projects is setup to 0.12.0 instead 0.12.0-snapshot

### ISSUE THREAD

**Issue by cvgaviao** [sonatype/sonatype-tycho#6]
tycho-maven-plugin is at 0.12.0-SNAPSHOT version but the demos is already setup for 0.12.0. 
This means that we can't build those demo projects.

<properties>
    <tycho-version>0.12.0</tycho-version>
  </properties>

**Comment by oberlies** [comment]
This is on purpose because 0.12.0 will come out very soon. If you want to build the demo projects, use the branch tycho-0.11.x

**Comment by cvgaviao** [comment]
well, ok...  
But my vision is that it is always better to have all projects on same version, independently of any situation that will come...
I would sugest you to use Maven Release where you can change all version of all projects POM same time ...

cheers
